export const reducerCases  = {
    SET_USER : "SET_USER",
    SET_EXPENSES: "SET_EXPENSES",
    SET_ADD_NEW_EXPENSE : "SET_ADD_NEW_EXPENSE",
    SET_ERROR : "SET_ERROR",
    SET_FILTER_YEAR: "SET_FILTER_YEAR",
    SET_RECORD_PER_PAGE: "SET_RECORD_PER_PAGE",
    SET_ADD_UPDATE : "SET_ADD_UPDATE",
    SET_TOTAL_MONTHLY_EXP: "SET_TOTAL_MONTHLY_EXP",
    SET_DELETE : "SET_DELETE",
}

